-- INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_id)
-- VALUES (1, '2001-12-23 14:39:53.662522-05', 'https://greenhealthycooking.com/6-healthy-breakfast-smoothies/', 'https://greenhealthycooking.com/wp-content/uploads/2018/05/Healthy-Breakfast-SMoothies.jpg', 'Healthy Breakfast Smoothies', 'These 6 delicious breakfast smoothies will give you all the energy you n eed to conquer your day.', 'The secret formula for healthy breakfast smoothies plus 6 super easy and simple 6-ingredient smoothie ideas. Many Healthy Breakfast Smoothies either require 20 ingredients OR are not that healthy at all actually. No need to overcomplicate things. Keep it simple with this amazing smoothie recipe formula. No protein powder required if you don’t like it. Includes recommended sources of protein, healthy fats, healthy carbs, and fiber.', 'Food and Drink', 1);
-- INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_id)
-- VALUES (1, '2021-06-21 15:41:53.662522-05', 'https://www.marthastewart.com/894554/pendulum-painting', 'https://i.pinimg.com/564x/58/60/6d/58606d50156ec5c2d2af2543d6717edf.jpg', 'Pendulum Paintings', 'All you need is gravity, paint, a canvas, and some rope to make these gorgeous pendulum paintings!', 'Pendulum paintings are taking the art world by storm. Science meets artistry in this beautiful collaboration that produces geometrically beautiful designs on every attempt. Set up your canvas on the ground, prepare a tall tripod and attach a rope to the top with the paint attached to the bottom - for larger paintings, you can affix the rope into your ceiling - open your paint and set the can circling in motion. Simply catch the paint when it reaches the end of its spin cycle, and you have made a beautiful work of art!', 'Arts and Crafts', 4);



INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (1, '2001-12-23 14:39:53.662522-05', 'https://greenhealthycooking.com/6-healthy-breakfast-smoothies/', 'https://greenhealthycooking.com/wp-content/uploads/2018/05/Healthy-Breakfast-SMoothies.jpg', 'Healthy Breakfast Smoothies', 'These 6 delicious breakfast smoothies will give you all the energy you n eed to conquer your day.', 'The secret formula for healthy breakfast smoothies plus 6 super easy and simple 6-ingredient smoothie ideas. Many Healthy Breakfast Smoothies either require 20 ingredients OR are not that healthy at all actually. No need to overcomplicate things. Keep it simple with this amazing smoothie recipe formula. No protein powder required if you don’t like it. Includes recommended sources of protein, healthy fats, healthy carbs, and fiber.', 'Food and Drink', 'Healthy Living', 'Breakfast', 'Smoothies');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (1, '2021-06-21 15:41:53.662522-05', 'https://www.marthastewart.com/894554/pendulum-painting', 'https://i.pinimg.com/564x/58/60/6d/58606d50156ec5c2d2af2543d6717edf.jpg', 'Pendulum Paintings', 'All you need is gravity, paint, a canvas, and some rope to make these gorgeous pendulum paintings!', 'Pendulum paintings are taking the art world by storm. Science meets artistry in this beautiful collaboration that produces geometrically beautiful designs on every attempt. Set up your canvas on the ground, prepare a tall tripod and attach a rope to the top with the paint attached to the bottom - for larger paintings, you can affix the rope into your ceiling - open your paint and set the can circling in motion. Simply catch the paint when it reaches the end of its spin cycle, and you have made a beautiful work of art!', 'Arts and Crafts', 'Paint', 'DIY', 'Gravity');

