INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (1, '2001-12-23 14:39:53.662522-05', 'https://greenhealthycooking.com/6-healthy-breakfast-smoothies/', 'https://greenhealthycooking.com/wp-content/uploads/2018/05/Healthy-Breakfast-SMoothies.jpg', 'Healthy Breakfast Smoothies', 'These 6 delicious breakfast smoothies will give you all the energy you n eed to conquer your day.', 'The secret formula for healthy breakfast smoothies plus 6 super easy and simple 6-ingredient smoothie ideas. Many Healthy Breakfast Smoothies either require 20 ingredients OR are not that healthy at all actually. No need to overcomplicate things. Keep it simple with this amazing smoothie recipe formula. No protein powder required if you don’t like it. Includes recommended sources of protein, healthy fats, healthy carbs, and fiber.', 'Food and Drink', 'Healthy Living', 'Breakfast', 'Smoothies');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (1, '2021-06-21 15:41:53.662522-05', 'https://www.marthastewart.com/894554/pendulum-painting', 'https://i.pinimg.com/564x/58/60/6d/58606d50156ec5c2d2af2543d6717edf.jpg', 'Pendulum Paintings', 'All you need is gravity, paint, a canvas, and some rope to make these gorgeous pendulum paintings!', 'Pendulum paintings are taking the art world by storm. Science meets artistry in this beautiful collaboration that produces geometrically beautiful designs on every attempt. Set up your canvas on the ground, prepare a tall tripod and attach a rope to the top with the paint attached to the bottom - for larger paintings, you can affix the rope into your ceiling - open your paint and set the can circling in motion. Simply catch the paint when it reaches the end of its spin cycle, and you have made a beautiful work of art!', 'Arts and Crafts', 'Paint', 'DIY', 'Gravity');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (2, '2021-05-20 11:44:53.662522-05', 'https://www.musicinminnesota.com/13-facts-taylor-swift-2019/', 'https://www.musicinminnesota.com/wp-content/uploads/2019/11/Taylor-Swift-80s-Style-758x556.jpg', 'Taylor Swift', 'Taylor Swift is arguably one of the biggest pop stars on the planet, so here is everything you should know about her!', 'Many people across the world love Taylor Swift, and they can’t get enough of her when it comes to interesting facts and information about her life. She is truly America’s sweetheart, and she has captivated audiences for over a decade. The link below takes you to 13 of the most fun facts that all fans of Taylor Swift should know.', 'Music', 'Taylor Swift', 'Pop', 'Celebrity');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (2, '2020-12-09 08:54:53.662522-05', 'https://www.musicinminnesota.com/13-facts-taylor-swift-2019/', 'https://www.intmath.com/basic-algebra/img/basic-algebra2.jpg', 'Taylor Swift', 'Algebra helps in the representation of problems or situations as mathematical expressions. It involves variables like x, y, z, and mathematical operations.', 'Algebra helps in the representation of problems or situations as mathematical expressions. It involves variables like x, y, z, and mathematical operations like addition, subtraction, multiplication, and division to form a meaningful mathematical expression. All the branches of mathematics such as trigonometry, calculus, coordinate geometry, involve the use of algebra. One simple example of an expression in algebra is 2x + 4 = 8.

Algebra deals with symbols and these symbols are related to each other with the help of operators. It is not just a mathematical concept, but a skill that all of us use in our daily life without even realizing it. Understanding algebra as a concept is more important than solving equations and finding the right answer, as it is useful in all the other topics of mathematics that you are going to learn in the future or you have already learned in past.', 'Education', 'Math', 'Algebra', 'Homework');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (3, '2021-05-20 11:44:53.662522-05', 'https://www.worldwildlife.org/species/red-panda', 'https://files.worldwildlife.org/wwfcmsprod/images/HERO_Red_Panda_279141/hero_full/7bkg4jrmln_XL_279141.jpg', 'Red Pandas', 'Red pandas are slightly larger than a domestic cat with a bear-like body and thick russet fur. The belly and limbs are black, and there are white markings on the side of the head and above its small eyes.', 'The red panda is slightly larger than a domestic cat with a bear-like body and thick russet fur. The belly and limbs are black, and there are white markings on the side of the head and above its small eyes. Red pandas are very skillful and acrobatic animals that predominantly stay in trees. Almost 50% of the red panda’s habitat is in the Eastern Himalayas. They use their long, bushy tails for balance and to cover themselves in winter, presumably for warmth. Primarily an herbivore, the name panda is said to come from the Nepali word ‘ponya,’ which means bamboo or plant eating animal.', 'Animals', 'Red Panda', 'Cute', 'Mammal');
INSERT INTO resources(owner_id, created_at, resource_url, thumbnail_photo_url, title, summary, description, category, tag_1, tag_2, tag_3)
VALUES (1, '2017-04-16 09:44:53.662522-05', 'https://www.tutorialspoint.com/mongodb/index.htm', 'https://static.javatpoint.com/mongodb/images/mongodb-tutorial.jpg', 'MongoDB', 'MongoDB is an open-source document database and leading NoSQL database. MongoDB is written in C++. This tutorial will give you great understanding on MongoDB concepts needed to create and deploy a highly scalable and performance-oriented database.', 'With MongoDB Atlas, your self-healing clusters are made up of geographically distributed database instances to ensure no single point of failure. Want even better availability guarantees? Get multi-region fault tolerance by enabling cross-region replication. MongoDB Atlas also includes powerful features to enhance reliability for your mission-critical production databases, such as continuous backups and point-in-time recovery.', 'Other', 'MongoDB', 'Database', 'Web Development');
